[dependencies]
prod = [ "dotenv", "valibot", "drizzle-orm", "pg", "better-auth", "@iarna/toml", "marked", "runed", "bits-ui", "tailwind-variants", "tailwind-merge", "css-variants",]
dev = [ "@types/node", "@types/pg", "drizzle-kit", "tsx", "sass-embedded", "utopia-core-scss",]

[database]
password = "password123"
name = "svelte"
username = "admin"

[user]
password = "password123"
email = "admin@example.com"
username = "admin"
name = "Svelte Admin"

[project]
location = "test_output"
git = true
description = "A SvelteKit Project"
title = "SvelteKit Project"

[container]
prefix = "svelte"
